<?php

namespace BookshareRestApiBundle\Repository;

/**
 * BookRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
