<?php

namespace BookshareRestApiBundle\Repository;

/**
 * CourierServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourierServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
