<?php

namespace BookshareRestApiBundle\Repository;

/**
 * DeliveryInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
