<?php

namespace BookshareRestApiBundle\Repository;

use BookshareRestApiBundle\Entity\Message;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new Mapping\ClassMetadata(Message::class) :
                $metadata
        );
    }

    /**
     * @param Message $message
     * @return bool
     */
    public function insert(Message $message) {
        try {
            $this->_em->persist($message);
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        } catch ( ORMException $e ) {
            return false;
        }
    }

    /**
     * @param Message $message
     * @return bool
     */
    public function remove(Message $message) {
        try {
            $this->_em->remove($message);
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        } catch ( ORMException $e ) {
            return false;
        }
    }
}
