<?php

namespace BookshareRestApiBundle\Repository;

use BookshareRestApiBundle\Entity\SuggestedBook;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

/**
 * SuggestedBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestedBooksRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new Mapping\ClassMetadata(SuggestedBook::class) :
                $metadata
        );
    }

    /**
     * @param SuggestedBook $suggestedBook
     * @return bool
     */
    public function insert(SuggestedBook $suggestedBook) {
        try {
            $this->_em->persist($suggestedBook);
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        } catch ( ORMException $e ) {
            return false;
        }
    }

    /**
     * @param SuggestedBook $suggestedBook
     * @return bool
     */
    public function remove(SuggestedBook $suggestedBook) {
        try {
            $this->_em->remove($suggestedBook);
            $this->_em->flush();
            return true;
        } catch ( OptimisticLockException $e ) {
            return false;
        } catch ( ORMException $e ) {
            return false;
        }
    }
}
