<?php

namespace BookshareRestApiBundle\Repository;

/**
 * SuggestedBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestedBooksRepository extends \Doctrine\ORM\EntityRepository
{
}
